version: "3.8"

services:
    app:
        image: laravelphp/php-fpm:8.0
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: user_password
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
