version: '3.8'

services:
  web:
    image: php:8.0-fpm
    container_name: laravel_web
    volumes:
      - .:/var/www
    networks:
      - laravel

  app:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - '80:80'
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
